config/routes.rb
Rails.application.routes.draw do
   

 

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :active
      match :active, to: :active, via: [:post, :patch]
      match :unactive, to: :unactive, via: [:post, :patch]
    end
  end

  

  
  get '/clearw', to: 'clears#new'
  post '/clearw', to: 'clears#create'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :albums
  resources :photos,          only: [:new, :create, :destroy]
  
  post '/upload', to: 'upload#create'
  post '/uploads_finish', to: 'upload#finish'
  delete '/delete_uploads', to: 'upload#destroy'

  resources :products

  resources :upcs
  resources :kwords
  resources :xstockplans
  resources :xstocks
  resources :etemplates

  resources :xstockplans do
    member do
      match :importexcel, to: :importexcel, via: [:post, :patch]
      match :exportexcel, to: :exportexcel, via: [:post, :patch]
    end
  end
  
  resources :albums do
    member do
     
      match :exportexcel, to: :exportexcel, via: [:post, :patch]
    end
    post :out_multiple, action: :outexcel, on: :collection
   
  end

  resources :photos do
    delete :destroy_multiple, action: :destroy, on: :collection
  end
  
  

  
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  include AlbumsHelper

  
  def home
    @users = User.where(activated: true).order(:id).take(8)
    
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])

    end
  end

  def help
    @colors = COLORS
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %> <h1>About</h1>
<p>
The <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorial</em></a> is a
<a href="http://www.railstutorial.org/book">book</a> and
<a href="http://screencasts.railstutorial.org/">screencast series</a> to teach web development with
<a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> <h1>Contact</h1>
<p>
      Contact the NBTCNET about the bbs app at the qq:232181579 or mail to
<a href="mailto:hxmusic@foxmaill.com">hxmusic@foxmail.com</a>. </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %> <h1>Help</h1>

<p>
 Get help about rails music guitar or ideas, see the
<a href="http://bbs.nbtcnet.com"><em>BBS NBTCNET</em></a>.
</p>
<p>
  About Rails <a href="http://news.railstutorial.org/" target='_blank'>News</a>
<p>

<div class="row">
  <div class="col-md-6">
    <h3>Color Code </h3>
       <table  id="myTable" class="table">
    <thead>
      <tr>

        <th>Code</th>
         <th>Color</th>
            <th>Name</th>
            <th>Amazon Name</th>
        </tr>

    </thead>
    <tbody>
      <% @colors.each do |f| %>
      <tr>
        <td><%= f.upcase %></td>
        <td style="background:<%= color_for f%>"></td>
        <td><%= color_for f %></td>
        <td><%= color_map_for f %></td>


      </tr>
      <% end %>

    </tbody>
     </table>
  </div>
  </div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
<section class="micropost_form">
  <%= render 'shared/micropost_form' %>
</section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
<%= render 'shared/feed' %>
</div>

      </div>
<% else %>

<div class="center jumbotron">
  <h1>Welcome to the XERP for AMAZON</h1>
  <h2>
    This is the home page for the
    <a href="http://www.nbtcnet.com/">nbtcnet</a> web solution.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>
<div class="center">
<%= link_to image_tag("logo.png", alt: "TCNET"),
    'http://www.nbtcnet.com/' %>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
    'http://rubyonrails.org/' %>
</div>
<div class="row center user_list">
  <ul class="">
<% @users.each do |user| %>
    <li>
     <%= link_to gravatar_for(user, size: 110), user %>
    </li>
    <% end %>
    </ul>
  </div>

<% end %>