config/routes.rb
Rails.application.routes.draw do
   

 

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :active
      match :active, to: :active, via: [:post, :patch]
      match :unactive, to: :unactive, via: [:post, :patch]
    end
  end

  

  
  get '/clearw', to: 'clears#new'
  post '/clearw', to: 'clears#create'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :albums
  resources :photos,          only: [:new, :create, :destroy]
  
  post '/upload', to: 'upload#create'
  post '/uploads_finish', to: 'upload#finish'
  delete '/delete_uploads', to: 'upload#destroy'

  resources :products

  resources :upcs
  resources :kwords
  resources :xstockplans
  resources :xstocks
  resources :etemplates

  resources :xstockplans do
    member do
      match :importexcel, to: :importexcel, via: [:post, :patch]
      match :exportexcel, to: :exportexcel, via: [:post, :patch]
    end
  end
  
  resources :albums do
    member do
     
      match :exportexcel, to: :exportexcel, via: [:post, :patch]
    end
    post :out_multiple, action: :outexcel, on: :collection
   
  end

  resources :photos do
    delete :destroy_multiple, action: :destroy, on: :collection
  end
  
  

  
  
  
end

app/models/kword.rb
class Kword < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/kwords_controller.rb
class KwordsController < ApplicationController
  include AlbumsHelper
  include KwordsHelper

  def new
    @kword = Kword.new
  end

  def create
    @kword = current_user.kwords.build(kword_params)
    @kword.outstr =clear_for kword_params[:instr],kword_params[:lefwords]
    if @kword.save
      flash[:success] = "Kword created!"
      redirect_to kwords_path
      
    else
      render 'new'
    end
  end

  def show
    @category = category_for current_user.kwords
    @kword = Kword.find(params[:id])
    
  end

  def edit
    @kword = Kword.find(params[:id])
   
  end

  def destroy
    Kword.find(params[:id]).destroy
    flash[:success] = "Kwords deleted"
    redirect_to kwords_path
  end

  def update
    @kword = Kword.find(params[:id])
   # kword_params[:outstr] = "new out"
    @kword.outstr =clear_for kword_params[:instr],kword_params[:lefwords]
    if @kword.update_attributes(kword_params)
      flash[:success] = "Kwords updated"
      redirect_to kwords_path
    else
      render 'edit'
    end
  end
  

  def index
    @category = category_for current_user.kwords
    
    sql = "name LIKE ?"
    #condition = params[:q].nil? "":"name like \%"+params[:q]+"\%"
   # @kwords = current_user.kwords.where(sql,"%#{params[:q]}%").paginate(page: params[:page])
    # @albums = current_user.albums.search(params[:q]).paginate(page: params[:page])
   # @kwords = current_user.kwords.all

    @kwords=current_user.kwords.paginate(page: params[:page])
  end
    

  private
  
    def kword_params
      params.require(:kword).permit(:name, :instr,:lefwords)
    end

  
  
end

app/helpers/kwords_helper.rb
# coding: utf-8
module KwordsHelper
  def clear_for(instr,lefwords)
    
    keywords_arry = instr.tr("\n\r","|").split('|').map{|x| x.strip}.uniq.delete_if{|x| !x.to_s.present?}
    lef_arry = lefwords.tr("\n\r","|").split('|').map{|x| x.strip}.uniq.delete_if{|x| !x.to_s.present?}
    s = keywords_arry
   
    lef_arry.each do |n|
      s= s.delete_if{|x| x.to_s.include?(n.to_s.chomp)}
    end
   

    return s.join("\n")
  end
end

app/views/kwords/_form.html.erb
<%= form_for(@kword) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :instr %>
     <%= f.text_area :instr, class: 'form-control',rows: 4,placeholder: "keywords use | or Enter to separate" %>
      <%= f.label :outstr %>
      <%= f.text_area :outstr, class: 'form-control',rows: 4,placeholder: "out string" %>

     <%= f.label :lefwords %>
     <%= f.text_area :lefwords, class: 'form-control',rows: 4 ,placeholder:"need clear words"%>


    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
 <% end %>

app/views/kwords/_kword.html.erb
dfd

app/views/kwords/_search.erb
<div class="row kwords_search">
      <ul>
        <% @category.each do |f|%>
        <li>

      <%= link_to f,kwords_path(:q => f) %>
</li>
      <% end %>
      </ul>
      </div>

      

app/views/kwords/edit.html.erb
<% provide(:title, "Edit kwords") %>
<% provide(:button_text, 'Save changes') %>
<div class="row">
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/kword_menu' %>
  </aside>
  <div class="col-md-9">
    <div class="col-md-9 col-md-offset-1">
 <h1>Edit kwords</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/kwords/index.html.erb
<% provide(:title, 'My keywords') %>

<div class="row">
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/kword_menu' %>
  </aside>
  <div class="col-md-9">

    <%= render 'search' %>


    <div class="row kwords">
      <table class="table">


      <% @kwords.each do |kword| %>
      <tr>
        <td>
          <%= link_to kword.name, kword %>

        </td>
        <td><p>
<%= link_to "edit",edit_kword_path(kword) %> | <%= link_to "delete", kword, method: :delete, data: { confirm: "You sure?"} %>
</p></td>
        </tr>

      <% end %>

  </table>
  </div>

 <%= will_paginate %>
  </div>

</div>

app/views/kwords/new.html.erb
<% provide(:title, 'New kwords') %>
<% provide(:button_text, 'Create my kwords') %>
<div class="row" >
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/kword_menu' %>
  </aside>
  <div class="col-md-9">

    <div class="col-md-6 col-md-offset-2">
     <h1>Create kwords</h1>
      <%= render 'form' %>
    </div>

  </div>

</div>

app/views/kwords/show.html.erb
<% provide(:title, "Show kwords") %>

<div class="row">
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/kword_menu' %>
  </aside>
  <div class="col-md-9">
    <%= render 'search' %>
    <section class="kword_info">


      <h5><%=@kword.name%></h5>
      <textarea class="form-control" rows="4"
                name="kinstr" id="kinstr"><%=@kword.instr %></textarea>
       <textarea class="form-control" rows="4"
                 name="koutstr" id="koutstr"><%=@kword.outstr %></textarea>
        <textarea class="form-control" rows="4"
                  name="lefwords" id="lefwords"><%=@kword.lefwords %></textarea>



<span><%= link_to "edit",edit_kword_path(@kword) %> | <%= link_to "delete", @kword, method: :delete, data: { confirm: "You sure?"} %></span>
</section>

<div>