config/routes.rb
Rails.application.routes.draw do
   

 

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :active
      match :active, to: :active, via: [:post, :patch]
      match :unactive, to: :unactive, via: [:post, :patch]
    end
  end

  

  
  get '/clearw', to: 'clears#new'
  post '/clearw', to: 'clears#create'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :albums
  resources :photos,          only: [:new, :create, :destroy]
  
  post '/upload', to: 'upload#create'
  post '/uploads_finish', to: 'upload#finish'
  delete '/delete_uploads', to: 'upload#destroy'

  resources :products

  resources :upcs
  resources :kwords
  resources :xstockplans
  resources :xstocks
  resources :etemplates

  resources :xstockplans do
    member do
      match :importexcel, to: :importexcel, via: [:post, :patch]
      match :exportexcel, to: :exportexcel, via: [:post, :patch]
    end
  end
  
  resources :albums do
    member do
     
      match :exportexcel, to: :exportexcel, via: [:post, :patch]
    end
    post :out_multiple, action: :outexcel, on: :collection
   
  end

  resources :photos do
    delete :destroy_multiple, action: :destroy, on: :collection
  end
  
  

  
  
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit,:show, :create, :destroy]

  def index
    @products = current_user.products.paginate(page: params[:page])
  end

  def new
    @product = Product.new
    
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success]= "Product updated"
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      flash[:success] = "Product created"
      redirect_to products_path
    else
      render 'new'
    end
    
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product deleted"
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :sku,:description)
    end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
     <%= f.label :sku %>
    <%= f.text_field :sku, class: 'form-control' %>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control',placeholder: "Description" %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
 <% end %>

app/views/products/_product.html.erb
<li>
  <span>
   <%= link_to product.name, product %>
  </span>
  <p>
<%= link_to "edit",edit_product_path(product) %> | <%= link_to "delete", product, method: :delete, data: { confirm: "You sure?"} %>
</p>
</li>

app/views/products/edit.html.erb
<% provide(:title, 'New products') %>
<% provide(:button_text, 'Save changes') %>
<div class="row">
  <aside class="col-md-3 products_menu">
   <%= render 'shared/product_menu' %>
  </aside>
  <div class="col-md-9">
    <h1>Edit product</h1>


   <div class="row ">
  <%= render 'form'%>
     </div>


  </div>

</div>

app/views/products/index.html.erb
<% provide(:title, 'My products') %>

<div class="row">
  <aside class="col-md-3 products_menu">
   <%= render 'shared/product_menu' %>
  </aside>
  <div class="col-md-9">
    <h1>My products</h1>


    <div class="row ">
      <ul>
        <%= render @products %>
        </ul>

     </div>
 <%= will_paginate %>


  </div>

</div>

app/views/products/new.html.erb
<% provide(:title, 'New products') %>
<% provide(:button_text, 'Create product') %>
<div class="row">
  <aside class="col-md-3 products_menu">
   <%= render 'shared/product_menu' %>
  </aside>
  <div class="col-md-9">
    <h1>New product</h1>


   <div class="row ">
  <%= render 'form'%>

     </div>


  </div>

</div>